name: Build Linux Binary

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller psutil

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconfirm --clean main.py

      - name: Rename binary
        run: |
          mv dist/main dist/mONuTILITY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mONuTILITY-linux
          path: dist/mONuTILITY
