
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller psutil

      - name: Windows deps
        if: runner.os == 'Windows'
        run: pip install windows-curses

      - name: Build
        run: pyinstaller --onefile --strip --noconfirm main.py

      - name: Rename executable
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/main.exe dist/mONuTILITY.exe
          else
            mv dist/main dist/mONuTILITY
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: dist/mONuTILITY*
